name: Deployment Docker image Backend

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check repository
        uses: actions/checkout@v3

      -
        name: Log to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@4
        with:
          images: pselak/better-schedule-backend

      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: pselak/better-schedule-backend:latest

